#!/usr/bin/ruby

## Include
require 'optparse'
require './iconFileName'

## Options
option_hash = {}
OptionParser.new{|opt|
  opt.on('--in VAL') {|v| option_hash[:in] = v}    
  opt.on('--out VAL') {|v| option_hash[:out] = v } 
  opt.parse!(ARGV)
}

# argument check
## @todo

# execute command
in_file = option_hash[:in]
out_dir = option_hash[:out]

$icon_array.each{|value|
  fname = value[:fname]
  size = value[:size]
  command = "sips --resampleHeight #{size} #{in_file} --out #{out_dir}/#{fname}"
  system(command)
}

