#!/usr/bin/ruby

## Include
require 'optparse'
require './iconFileName'

## Options
option_hash = {}
OptionParser.new{|opt|
  opt.on('--in VAL') {|v| option_hash[:in] = v}    
  opt.on('--out VAL') {|v| option_hash[:out] = v } 
  opt.parse!(ARGV)
}

# p option_hash
# puts $0
# ARGV.each {|arg| puts ": #{arg}!"}
# print($hello)

# argument check

# execute command
$icon_array.each{|value|
  fname = value[:fname]
  size = value[:size]
  command = "echo #{fname} #{size}"
  system(command)
}

